spring.application.name=salesforce-app

# SALESFORCE
salesforce.client.id=YOUR_REAL_CLIENT_ID
salesforce.client.secret=YOUR_REAL_SECRET
salesforce.redirect-uri=http://localhost:8080/auth/callback
salesforce.auth-url=https://login.salesforce.com/services/oauth2/authorize
salesforce.token-url=https://login.salesforce.com/services/oauth2/token
salesforce.api-version=v59.0

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/salesforce_rule_manager
spring.datasource.username=root
spring.datasource.password=Shreya@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080
frontend.url=http://localhost:5173
