spring.application.name=salesforce-app

# SALESFORCE
salesforce.client-id=you_client_id
salesforce.client-secret=your_secret_id
salesforce.redirect-uri=https://salesforceapp-production.up.railway.app/auth/callback
salesforce.auth-url=https://login.salesforce.com/services/oauth2/authorize
salesforce.token-url=https://login.salesforce.com/services/oauth2/token
salesforce.api-version=v59.0

# MYSQL
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=rfJqqhmQWthFjZiysgpFeHHGaoUdyXLm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=8080
frontend.url=https://salesforce-rule-manager-sooty.vercel.app
